// Entries of em13's archive that its code addresses with ARC() / EM_ARC(), generated by
// tools/arc_names.py. MOT is a motion, SEQ a sequence table, BIN a model, TPL textures, ENT an
// empty entry. The word after the type is the routine that plays the motion or the model's
// role; a hex number means the entry has no name yet.
#ifndef ARC_EM13_H
#define ARC_EM13_H

#define EM13_BIN_1BC            0x1BC
#define EM13_TPL_1BD            0x1BD
#define EM13_BIN_1BE            0x1BE
#define EM13_BIN_1BF            0x1BF
#define EM13_BIN_1C0            0x1C0
#define EM13_BIN_1C1            0x1C1
#define EM13_BIN_1C2            0x1C2
#define EM13_BIN_1C3            0x1C3
#define EM13_BIN_1C4            0x1C4
#define EM13_BIN_1C5            0x1C5
#define EM13_BIN_1C6            0x1C6
#define EM13_BIN_1C7            0x1C7
#define EM13_BIN_1C8            0x1C8
#define EM13_BIN_1D8            0x1D8
#define EM13_TPL_1D9            0x1D9
#define EM13_BIN_1DA            0x1DA
#define EM13_BIN_1DB            0x1DB
#define EM13_BIN_1DC            0x1DC
#define EM13_TPL_1DD            0x1DD
#define EM13_BIN_1DE            0x1DE
#define EM13_BIN_1DF            0x1DF
#define EM13_BIN_1E0            0x1E0
#define EM13_TPL_1E1            0x1E1
#define EM13_BIN_1E2            0x1E2
#define EM13_BIN_1E3            0x1E3
#define EM13_BIN_1E7            0x1E7
#define EM13_TPL_1E8            0x1E8
#define EM13_BIN_1E9            0x1E9
#define EM13_TPL_1EA            0x1EA
#define EM13_BIN_1ED            0x1ED
#define EM13_BIN_1EE            0x1EE
#define EM13_BIN_1EF            0x1EF
#define EM13_BIN_1F0            0x1F0
#define EM13_TPL_1F1            0x1F1
#define EM13_BIN_1F4            0x1F4
#define EM13_BIN_1F5            0x1F5
#define EM13_BIN_1F6            0x1F6
#define EM13_BIN_1F7            0x1F7
#define EM13_BIN_1F8            0x1F8
#define EM13_BIN_1F9            0x1F9
#define EM13_BIN_1FA            0x1FA
#define EM13_BIN_1FB            0x1FB
#define EM13_BIN_WEAPON_SET_254 0x254
#define EM13_TPL_WEAPON_SET_255 0x255
#define EM13_BIN_WEAPON_SET_256 0x256
#define EM13_TPL_WEAPON_SET_257 0x257
#define EM13_MOT_WEAPON_SET_258 0x258
#define EM13_MOT_WEAPON_SET_259 0x259
#define EM13_MOT_WEAPON_SET_25A 0x25A
#define EM13_BIN_WEAPON_SET_25B 0x25B
#define EM13_TPL_WEAPON_SET_25C 0x25C
#define EM13_MOT_WEAPON_SET_25D 0x25D
#define EM13_MOT_WEAPON_SET_25E 0x25E
#define EM13_BIN_WEAPON_SET_25F 0x25F
#define EM13_TPL_WEAPON_SET_260 0x260
#define EM13_TPL_WEAPON_SET_261 0x261
#define EM13_BIN_WEAPON_SET_262 0x262
#define EM13_TPL_WEAPON_SET_263 0x263
#define EM13_TPL_WEAPON_SET_264 0x264
#define EM13_BIN_WEAPON_SET_265 0x265
#define EM13_TPL_WEAPON_SET_266 0x266
#define EM13_TPL_WEAPON_SET_267 0x267
#define EM13_BIN_WEAPON_SET_268 0x268
#define EM13_TPL_WEAPON_SET_269 0x269
#define EM13_BIN_WEAPON_SET_26A 0x26A
#define EM13_TPL_WEAPON_SET_26B 0x26B
#define EM13_BIN_WEAPON_SET_26C 0x26C
#define EM13_TPL_WEAPON_SET_26D 0x26D
#define EM13_BIN_WEAPON_SET_270 0x270
#define EM13_TPL_WEAPON_SET_271 0x271

#endif  // ARC_EM13_H
