// Entries of em14's archive that its code addresses with ARC() / EM_ARC(), generated by
// tools/arc_names.py. MOT is a motion, SEQ a sequence table, BIN a model, TPL textures, ENT an
// empty entry. The word after the type is the routine that plays the motion or the model's
// role; a hex number means the entry has no name yet.
#ifndef ARC_EM14_H
#define ARC_EM14_H

#define EM14_BIN_1E7            0x1E7
#define EM14_TPL_1E8            0x1E8
#define EM14_BIN_1E9            0x1E9
#define EM14_TPL_1EA            0x1EA
#define EM14_BIN_1ED            0x1ED
#define EM14_BIN_1EE            0x1EE
#define EM14_BIN_1EF            0x1EF
#define EM14_BIN_1F0            0x1F0
#define EM14_TPL_1F1            0x1F1
#define EM14_BIN_1F4            0x1F4
#define EM14_BIN_1F5            0x1F5
#define EM14_BIN_1F6            0x1F6
#define EM14_BIN_1F7            0x1F7
#define EM14_BIN_1F8            0x1F8
#define EM14_BIN_1F9            0x1F9
#define EM14_BIN_1FA            0x1FA
#define EM14_BIN_1FB            0x1FB
#define EM14_BIN_1FC            0x1FC
#define EM14_TPL_1FD            0x1FD
#define EM14_BIN_1FE            0x1FE
#define EM14_BIN_1FF            0x1FF
#define EM14_BIN_200            0x200
#define EM14_TPL_201            0x201
#define EM14_BIN_202            0x202
#define EM14_BIN_203            0x203
#define EM14_BIN_204            0x204
#define EM14_BIN_205            0x205
#define EM14_BIN_206            0x206
#define EM14_BIN_207            0x207
#define EM14_BIN_208            0x208
#define EM14_BIN_209            0x209
#define EM14_BIN_20A            0x20A
#define EM14_BIN_20B            0x20B
#define EM14_BIN_20C            0x20C
#define EM14_BIN_20D            0x20D
#define EM14_TPL_20E            0x20E
#define EM14_BIN_20F            0x20F
#define EM14_TPL_210            0x210
#define EM14_BIN_211            0x211
#define EM14_TPL_212            0x212
#define EM14_BIN_213            0x213
#define EM14_TPL_214            0x214
#define EM14_BIN_215            0x215
#define EM14_TPL_216            0x216
#define EM14_BIN_217            0x217
#define EM14_TPL_218            0x218
#define EM14_TPL_219            0x219
#define EM14_TPL_21A            0x21A
#define EM14_BIN_21B            0x21B
#define EM14_TPL_21C            0x21C
#define EM14_BIN_21D            0x21D
#define EM14_TPL_21E            0x21E
#define EM14_BIN_21F            0x21F
#define EM14_BIN_WEAPON_SET_26E 0x26E
#define EM14_TPL_WEAPON_SET_26F 0x26F
#define EM14_BIN_WEAPON_SET_270 0x270
#define EM14_TPL_WEAPON_SET_271 0x271
#define EM14_BIN_WEAPON_SET_272 0x272
#define EM14_TPL_WEAPON_SET_273 0x273
#define EM14_BIN_WEAPON_SET_274 0x274
#define EM14_TPL_WEAPON_SET_275 0x275
#define EM14_BIN_WEAPON_SET_276 0x276
#define EM14_TPL_WEAPON_SET_277 0x277

#endif  // ARC_EM14_H
