// Entries of em15's archive that its code addresses with ARC() / EM_ARC(), generated by
// tools/arc_names.py. MOT is a motion, SEQ a sequence table, BIN a model, TPL textures, ENT an
// empty entry. The word after the type is the routine that plays the motion or the model's
// role; a hex number means the entry has no name yet.
#ifndef ARC_EM15_H
#define ARC_EM15_H

#define EM15_BIN_WEAPON_SET_104 0x104
#define EM15_TPL_WEAPON_SET_105 0x105
#define EM15_BIN_WEAPON_SET_106 0x106
#define EM15_BIN_1BC            0x1BC
#define EM15_TPL_1BD            0x1BD
#define EM15_BIN_1BE            0x1BE
#define EM15_BIN_1BF            0x1BF
#define EM15_BIN_1C0            0x1C0
#define EM15_BIN_1C1            0x1C1
#define EM15_BIN_1C2            0x1C2
#define EM15_BIN_1C3            0x1C3
#define EM15_BIN_1C4            0x1C4
#define EM15_BIN_1C5            0x1C5
#define EM15_BIN_1C6            0x1C6
#define EM15_BIN_1C7            0x1C7
#define EM15_BIN_1C8            0x1C8
#define EM15_BIN_1C9            0x1C9
#define EM15_TPL_1CA            0x1CA
#define EM15_BIN_1CB            0x1CB
#define EM15_BIN_1CC            0x1CC
#define EM15_BIN_1D3            0x1D3
#define EM15_TPL_1D4            0x1D4
#define EM15_TPL_1D5            0x1D5
#define EM15_BIN_WEAPON_SET_1D6 0x1D6
#define EM15_TPL_WEAPON_SET_1D7 0x1D7
#define EM15_BIN_1DC            0x1DC
#define EM15_TPL_1DD            0x1DD
#define EM15_BIN_1DE            0x1DE
#define EM15_BIN_1DF            0x1DF
#define EM15_BIN_1E0            0x1E0
#define EM15_TPL_1E1            0x1E1
#define EM15_BIN_1E2            0x1E2
#define EM15_BIN_1E3            0x1E3
#define EM15_BIN_1E4            0x1E4
#define EM15_TPL_1E5            0x1E5
#define EM15_TPL_1E6            0x1E6
#define EM15_BIN_WEAPON_SET_254 0x254
#define EM15_TPL_WEAPON_SET_255 0x255
#define EM15_BIN_WEAPON_SET_256 0x256
#define EM15_TPL_WEAPON_SET_257 0x257
#define EM15_MOT_WEAPON_SET_258 0x258
#define EM15_MOT_WEAPON_SET_259 0x259
#define EM15_MOT_WEAPON_SET_25A 0x25A
#define EM15_BIN_WEAPON_SET_25B 0x25B
#define EM15_TPL_WEAPON_SET_25C 0x25C
#define EM15_MOT_WEAPON_SET_25D 0x25D
#define EM15_MOT_WEAPON_SET_25E 0x25E
#define EM15_BIN_WEAPON_SET_25F 0x25F
#define EM15_TPL_WEAPON_SET_260 0x260
#define EM15_TPL_WEAPON_SET_261 0x261
#define EM15_BIN_WEAPON_SET_265 0x265
#define EM15_TPL_WEAPON_SET_266 0x266
#define EM15_TPL_WEAPON_SET_267 0x267
#define EM15_BIN_WEAPON_SET_268 0x268
#define EM15_TPL_WEAPON_SET_269 0x269
#define EM15_BIN_WEAPON_SET_26A 0x26A
#define EM15_TPL_WEAPON_SET_26B 0x26B
#define EM15_BIN_WEAPON_SET_26C 0x26C
#define EM15_TPL_WEAPON_SET_26D 0x26D
#define EM15_BIN_WEAPON_SET_270 0x270
#define EM15_TPL_WEAPON_SET_271 0x271

#endif  // ARC_EM15_H
