// Entries of em17's archive that its code addresses with ARC() / EM_ARC(), generated by
// tools/arc_names.py. MOT is a motion, SEQ a sequence table, BIN a model, TPL textures, ENT an
// empty entry. The word after the type is the routine that plays the motion or the model's
// role; a hex number means the entry has no name yet.
#ifndef ARC_EM17_H
#define ARC_EM17_H

#define EM17_BIN_1BC            0x1BC
#define EM17_TPL_1BD            0x1BD
#define EM17_BIN_1BE            0x1BE
#define EM17_BIN_1BF            0x1BF
#define EM17_BIN_1C0            0x1C0
#define EM17_BIN_1C1            0x1C1
#define EM17_BIN_1C2            0x1C2
#define EM17_BIN_1C3            0x1C3
#define EM17_BIN_1C4            0x1C4
#define EM17_BIN_1C5            0x1C5
#define EM17_BIN_1C6            0x1C6
#define EM17_BIN_1C7            0x1C7
#define EM17_BIN_1C8            0x1C8
#define EM17_BIN_1CD            0x1CD
#define EM17_TPL_1CE            0x1CE
#define EM17_BIN_1CF            0x1CF
#define EM17_BIN_1D0            0x1D0
#define EM17_BIN_1D3            0x1D3
#define EM17_TPL_1D4            0x1D4
#define EM17_TPL_1D5            0x1D5
#define EM17_BIN_WEAPON_SET_1D6 0x1D6
#define EM17_TPL_WEAPON_SET_1D7 0x1D7
#define EM17_BIN_1D8            0x1D8
#define EM17_TPL_1D9            0x1D9
#define EM17_BIN_1DA            0x1DA
#define EM17_BIN_1DB            0x1DB
#define EM17_BIN_1DC            0x1DC
#define EM17_TPL_1DD            0x1DD
#define EM17_BIN_1DE            0x1DE
#define EM17_BIN_1DF            0x1DF
#define EM17_BIN_WEAPON_SET_254 0x254
#define EM17_TPL_WEAPON_SET_255 0x255
#define EM17_BIN_WEAPON_SET_25F 0x25F
#define EM17_TPL_WEAPON_SET_260 0x260
#define EM17_TPL_WEAPON_SET_261 0x261
#define EM17_BIN_WEAPON_SET_265 0x265
#define EM17_TPL_WEAPON_SET_266 0x266
#define EM17_TPL_WEAPON_SET_267 0x267
#define EM17_BIN_WEAPON_SET_268 0x268
#define EM17_TPL_WEAPON_SET_269 0x269
#define EM17_BIN_WEAPON_SET_26A 0x26A
#define EM17_TPL_WEAPON_SET_26B 0x26B
#define EM17_BIN_WEAPON_SET_26C 0x26C
#define EM17_TPL_WEAPON_SET_26D 0x26D
#define EM17_BIN_WEAPON_SET_270 0x270
#define EM17_TPL_WEAPON_SET_271 0x271

#endif  // ARC_EM17_H
