// Entries of em18's archive that its code addresses with ARC() / EM_ARC(), generated by
// tools/arc_names.py. MOT is a motion, SEQ a sequence table, BIN a model, TPL textures, ENT an
// empty entry. The word after the type is the routine that plays the motion or the model's
// role; a hex number means the entry has no name yet.
#ifndef ARC_EM18_H
#define ARC_EM18_H

#define EM18_EFF_004                 0x004
#define EM18_BIN_005                 0x005
#define EM18_TPL_006                 0x006
#define EM18_BIN_007                 0x007
#define EM18_TPL_008                 0x008
#define EM18_BIN_CLOTH_PARTS_SET_00B 0x00B
#define EM18_BIN_CLOTH_PARTS_SET_00C 0x00C
#define EM18_BIN_GOODS_PARTS_SET     0x00D
#define EM18_BIN_00E                 0x00E
#define EM18_TPL_00F                 0x00F
#define EM18_BIN_HAND_SET_012        0x012
#define EM18_BIN_HAND_SET_013        0x013
#define EM18_MOT_014                 0x014
#define EM18_MOT_TRADE_015           0x015
#define EM18_MOT_TRADE_017           0x017
#define EM18_MOT_DIE_NORMAL          0x018

#endif  // ARC_EM18_H
