// Entries of em1c's archive that its code addresses with ARC() / EM_ARC(), generated by
// tools/arc_names.py. MOT is a motion, SEQ a sequence table, BIN a model, TPL textures, ENT an
// empty entry. The word after the type is the routine that plays the motion or the model's
// role; a hex number means the entry has no name yet.
#ifndef ARC_EM1C_H
#define ARC_EM1C_H

#define EM1C_BIN_1FC            0x1FC
#define EM1C_TPL_1FD            0x1FD
#define EM1C_BIN_1FE            0x1FE
#define EM1C_BIN_1FF            0x1FF
#define EM1C_BIN_200            0x200
#define EM1C_TPL_201            0x201
#define EM1C_BIN_202            0x202
#define EM1C_BIN_203            0x203
#define EM1C_BIN_204            0x204
#define EM1C_BIN_205            0x205
#define EM1C_BIN_206            0x206
#define EM1C_BIN_207            0x207
#define EM1C_BIN_208            0x208
#define EM1C_BIN_209            0x209
#define EM1C_BIN_20A            0x20A
#define EM1C_BIN_20B            0x20B
#define EM1C_BIN_20C            0x20C
#define EM1C_BIN_20D            0x20D
#define EM1C_TPL_20E            0x20E
#define EM1C_BIN_20F            0x20F
#define EM1C_TPL_210            0x210
#define EM1C_BIN_211            0x211
#define EM1C_TPL_212            0x212
#define EM1C_BIN_213            0x213
#define EM1C_TPL_214            0x214
#define EM1C_BIN_215            0x215
#define EM1C_TPL_216            0x216
#define EM1C_BIN_217            0x217
#define EM1C_TPL_218            0x218
#define EM1C_TPL_219            0x219
#define EM1C_BIN_21D            0x21D
#define EM1C_TPL_21E            0x21E
#define EM1C_BIN_21F            0x21F
#define EM1C_BIN_221            0x221
#define EM1C_TPL_222            0x222
#define EM1C_BIN_223            0x223
#define EM1C_TPL_224            0x224
#define EM1C_BIN_WEAPON_SET_26E 0x26E
#define EM1C_TPL_WEAPON_SET_26F 0x26F
#define EM1C_BIN_WEAPON_SET_270 0x270
#define EM1C_TPL_WEAPON_SET_271 0x271
#define EM1C_BIN_WEAPON_SET_272 0x272
#define EM1C_TPL_WEAPON_SET_273 0x273
#define EM1C_BIN_WEAPON_SET_274 0x274
#define EM1C_TPL_WEAPON_SET_275 0x275
#define EM1C_BIN_WEAPON_SET_276 0x276
#define EM1C_TPL_WEAPON_SET_277 0x277

#endif  // ARC_EM1C_H
