// Entries of em1e's archive that its code addresses with ARC() / EM_ARC(), generated by
// tools/arc_names.py. MOT is a motion, SEQ a sequence table, BIN a model, TPL textures, ENT an
// empty entry. The word after the type is the routine that plays the motion or the model's
// role; a hex number means the entry has no name yet.
#ifndef ARC_EM1E_H
#define ARC_EM1E_H

#define EM1E_BIN_1E7            0x1E7
#define EM1E_TPL_1E8            0x1E8
#define EM1E_BIN_1E9            0x1E9
#define EM1E_TPL_1EA            0x1EA
#define EM1E_BIN_1ED            0x1ED
#define EM1E_BIN_1EE            0x1EE
#define EM1E_BIN_1EF            0x1EF
#define EM1E_BIN_1F0            0x1F0
#define EM1E_TPL_1F1            0x1F1
#define EM1E_BIN_1F4            0x1F4
#define EM1E_BIN_1F5            0x1F5
#define EM1E_BIN_1F6            0x1F6
#define EM1E_BIN_1F7            0x1F7
#define EM1E_BIN_1F8            0x1F8
#define EM1E_BIN_1F9            0x1F9
#define EM1E_BIN_1FA            0x1FA
#define EM1E_BIN_1FB            0x1FB
#define EM1E_BIN_22F            0x22F
#define EM1E_TPL_230            0x230
#define EM1E_BIN_231            0x231
#define EM1E_TPL_232            0x232
#define EM1E_BIN_233            0x233
#define EM1E_BIN_234            0x234
#define EM1E_BIN_235            0x235
#define EM1E_BIN_236            0x236
#define EM1E_BIN_237            0x237
#define EM1E_BIN_238            0x238
#define EM1E_BIN_239            0x239
#define EM1E_BIN_23A            0x23A
#define EM1E_BIN_23B            0x23B
#define EM1E_BIN_23C            0x23C
#define EM1E_BIN_247            0x247
#define EM1E_TPL_248            0x248
#define EM1E_BIN_249            0x249
#define EM1E_TPL_24A            0x24A
#define EM1E_BIN_24B            0x24B
#define EM1E_TPL_24C            0x24C
#define EM1E_BIN_24D            0x24D
#define EM1E_TPL_24E            0x24E
#define EM1E_BIN_WEAPON_SET_26A 0x26A
#define EM1E_TPL_WEAPON_SET_26B 0x26B
#define EM1E_BIN_WEAPON_SET_26C 0x26C
#define EM1E_TPL_WEAPON_SET_26D 0x26D
#define EM1E_BIN_WEAPON_SET_270 0x270
#define EM1E_TPL_WEAPON_SET_271 0x271
#define EM1E_BIN_WEAPON_SET_272 0x272
#define EM1E_TPL_WEAPON_SET_273 0x273
#define EM1E_BIN_WEAPON_SET_274 0x274
#define EM1E_TPL_WEAPON_SET_275 0x275
#define EM1E_BIN_WEAPON_SET_276 0x276
#define EM1E_TPL_WEAPON_SET_277 0x277
#define EM1E_EFF_278            0x278

#endif  // ARC_EM1E_H
