// Entries of em20's archive that its code addresses with ARC() / EM_ARC(), generated by
// tools/arc_names.py. MOT is a motion, SEQ a sequence table, BIN a model, TPL textures, ENT an
// empty entry. The word after the type is the routine that plays the motion or the model's
// role; a hex number means the entry has no name yet.
#ifndef ARC_EM20_H
#define ARC_EM20_H

#define EM20_BIN_WEAPON_SET_104 0x104
#define EM20_TPL_WEAPON_SET_105 0x105
#define EM20_BIN_1E0            0x1E0
#define EM20_TPL_1E1            0x1E1
#define EM20_BIN_22F            0x22F
#define EM20_TPL_230            0x230
#define EM20_BIN_231            0x231
#define EM20_TPL_232            0x232
#define EM20_BIN_233            0x233
#define EM20_BIN_234            0x234
#define EM20_BIN_235            0x235
#define EM20_BIN_236            0x236
#define EM20_BIN_237            0x237
#define EM20_BIN_238            0x238
#define EM20_BIN_239            0x239
#define EM20_BIN_23A            0x23A
#define EM20_BIN_23B            0x23B
#define EM20_BIN_23C            0x23C
#define EM20_BIN_247            0x247
#define EM20_TPL_248            0x248
#define EM20_BIN_249            0x249
#define EM20_TPL_24A            0x24A
#define EM20_BIN_24B            0x24B
#define EM20_TPL_24C            0x24C
#define EM20_BIN_24D            0x24D
#define EM20_TPL_24E            0x24E
#define EM20_BIN_WEAPON_SET_26A 0x26A
#define EM20_TPL_WEAPON_SET_26B 0x26B
#define EM20_BIN_WEAPON_SET_26C 0x26C
#define EM20_TPL_WEAPON_SET_26D 0x26D
#define EM20_BIN_WEAPON_SET_270 0x270
#define EM20_TPL_WEAPON_SET_271 0x271
#define EM20_BIN_WEAPON_SET_272 0x272
#define EM20_TPL_WEAPON_SET_273 0x273
#define EM20_BIN_WEAPON_SET_274 0x274
#define EM20_TPL_WEAPON_SET_275 0x275
#define EM20_BIN_WEAPON_SET_276 0x276
#define EM20_TPL_WEAPON_SET_277 0x277
#define EM20_EFF_278            0x278

#endif  // ARC_EM20_H
