// Entries of em21's archive that its code addresses with ARC() / EM_ARC(), generated by
// tools/arc_names.py. MOT is a motion, SEQ a sequence table, BIN a model, TPL textures, ENT an
// empty entry. The word after the type is the routine that plays the motion or the model's
// role; a hex number means the entry has no name yet.
#ifndef ARC_EM21_H
#define ARC_EM21_H

#define EM21_BIN_004               0x004
#define EM21_TPL_005               0x005
#define EM21_TPL_006               0x006
#define EM21_MOT_007               0x007
#define EM21_MOT_008               0x008
#define EM21_MOT_009               0x009
#define EM21_MOT_00A               0x00A
#define EM21_MOT_00B               0x00B
#define EM21_MOT_WAIT              0x00C
#define EM21_SEQ_00D               0x00D
#define EM21_SEQ_00E               0x00E
#define EM21_SEQ_00F               0x00F
#define EM21_SEQ_010               0x010
#define EM21_SEQ_011               0x011
#define EM21_SEQ_012               0x012
#define EM21_SEQ_ESCAPE_013        0x013
#define EM21_SEQ_ESCAPE_014        0x014
#define EM21_SEQ_ESCAPE_015        0x015
#define EM21_SEQ_016               0x016
#define EM21_SEQ_WAIT              0x017
#define EM21_MOT_R100_TRAP_WAIT    0x018
#define EM21_MOT_R100_TRAP_CANCEL  0x019
#define EM21_MOT_01A               0x01A
#define EM21_MOT_PL_EM_TRAP_CANCEL 0x01B
#define EM21_SEQ_R100_TRAP_CANCEL  0x01C
#define EM21_SEQ_01D               0x01D
#define EM21_MOT_R100_ESCAPE       0x01E
#define EM21_MOT_VS_ELGIGANTE_01F  0x01F
#define EM21_MOT_VS_ELGIGANTE_020  0x020
#define EM21_MOT_VS_ELGIGANTE_021  0x021
#define EM21_SEQ_VS_ELGIGANTE_022  0x022
#define EM21_SEQ_VS_ELGIGANTE_023  0x023
#define EM21_MOT_VS_ELGIGANTE_024  0x024
#define EM21_MOT_VS_ELGIGANTE_025  0x025
#define EM21_MOT_VS_ELGIGANTE_026  0x026
#define EM21_SEQ_VS_ELGIGANTE_027  0x027

#endif  // ARC_EM21_H
