// Entries of em22's archive that its code addresses with ARC() / EM_ARC(), generated by
// tools/arc_names.py. MOT is a motion, SEQ a sequence table, BIN a model, TPL textures, ENT an
// empty entry. The word after the type is the routine that plays the motion or the model's
// role; a hex number means the entry has no name yet.
#ifndef ARC_EM22_H
#define ARC_EM22_H

#define EM22_BIN_004                      0x004
#define EM22_TPL_005                      0x005
#define EM22_EFF_006                      0x006
#define EM22_MOT_007                      0x007
#define EM22_MOT_SET_RUN_MOTION           0x009
#define EM22_MOT_R11_B_B_00B              0x00B
#define EM22_MOT_R11_B_B_00C              0x00C
#define EM22_MOT_00D                      0x00D
#define EM22_MOT_00E                      0x00E
#define EM22_MOT_SIDE_STEP                0x00F
#define EM22_MOT_DM_SMALL_010             0x010
#define EM22_MOT_DM_BLOW_011              0x011
#define EM22_MOT_DM_BLOW_012              0x012
#define EM22_MOT_DM_BLOW_013              0x013
#define EM22_MOT_WAKEUP_014               0x014
#define EM22_MOT_WAKEUP_015               0x015
#define EM22_MOT_JUMP_ATK                 0x016
#define EM22_MOT_JUMP_ATK_HIT_017         0x017
#define EM22_MOT_JUMP_ATK_HIT_018         0x018
#define EM22_MOT_JUMP_ATK_HIT_019         0x019
#define EM22_MOT_JUMP_ATK_HIT_01A         0x01A
#define EM22_SEQ_SET_RUN_MOTION_021       0x021
#define EM22_SEQ_SET_RUN_MOTION_022       0x022
#define EM22_SEQ_SET_RUN_MOTION_023       0x023
#define EM22_SEQ_SET_RUN_MOTION_024       0x024
#define EM22_SEQ_SET_RUN_MOTION_025       0x025
#define EM22_SEQ_027                      0x027
#define EM22_SEQ_02C                      0x02C
#define EM22_SEQ_SIDE_STEP                0x02D
#define EM22_SEQ_DM_BLOW_02E              0x02E
#define EM22_SEQ_DM_BLOW_02F              0x02F
#define EM22_SEQ_DM_BLOW_030              0x030
#define EM22_SEQ_WAKEUP_031               0x031
#define EM22_SEQ_WAKEUP_032               0x032
#define EM22_SEQ_JUMP_ATK                 0x033
#define EM22_SEQ_JUMP_ATK_HIT             0x034
#define EM22_MOT_PL_JUMP_ATK_HIT_035      0x035
#define EM22_MOT_PL_JUMP_ATK_HIT_036      0x036
#define EM22_MOT_PL_JUMP_ATK_HIT_037      0x037
#define EM22_MOT_PL_JUMP_ATK_HIT_038      0x038
#define EM22_BIN_SET_PARASITE             0x039
#define EM22_TPL_SET_PARASITE             0x03A
#define EM22_MOT_SET_PARASITE             0x03B
#define EM22_MOT_JUMP                     0x03C
#define EM22_SEQ_JUMP                     0x03D
#define EM22_MOT_TURN_03E                 0x03E
#define EM22_MOT_TURN_03F                 0x03F
#define EM22_MOT_ESCAPE                   0x040
#define EM22_SEQ_TURN_041                 0x041
#define EM22_SEQ_TURN_042                 0x042
#define EM22_SEQ_ESCAPE                   0x043
#define EM22_MOT_044                      0x044
#define EM22_MOT_DM_SMALL_045             0x045
#define EM22_SEQ_046                      0x046
#define EM22_BIN_SET_PARASITE_ATK         0x047
#define EM22_TPL_SET_PARASITE_ATK         0x048
#define EM22_MOT_049                      0x049
#define EM22_MOT_PARA_SET_MOT_ATK_HIT_04A 0x04A
#define EM22_MOT_PARA_SET_MOT_ATK_HIT_04B 0x04B
#define EM22_MOT_PARA_SET_MOT_ATK         0x04C
#define EM22_MOT_PL_PARA_ATK_HIT          0x04D
#define EM22_MOT_PARA_ATK_HIT             0x04F
#define EM22_MOT_PARA_ATK                 0x050
#define EM22_SEQ_PARA_ATK                 0x052
#define EM22_MOT_DM_BLOW_053              0x053
#define EM22_MOT_DM_BLOW_054              0x054
#define EM22_MOT_DM_BLOW_055              0x055
#define EM22_MOT_DM_BLOW_056              0x056
#define EM22_MOT_DM_BLOW_057              0x057
#define EM22_MOT_DM_BLOW_058              0x058
#define EM22_MOT_JUMP_WAIT                0x059
#define EM22_SEQ_JUMP_WAIT                0x05A

#endif  // ARC_EM22_H
