// Entries of em23's archive that its code addresses with ARC() / EM_ARC(), generated by
// tools/arc_names.py. MOT is a motion, SEQ a sequence table, BIN a model, TPL textures, ENT an
// empty entry. The word after the type is the routine that plays the motion or the model's
// role; a hex number means the entry has no name yet.
#ifndef ARC_EM23_H
#define ARC_EM23_H

#define EM23_EFF_004           0x004
#define EM23_BIN_005           0x005
#define EM23_BIN_SET_WING_006  0x006
#define EM23_BIN_SET_WING_007  0x007
#define EM23_TPL_008           0x008
#define EM23_MOT_009           0x009
#define EM23_MOT_00A           0x00A
#define EM23_MOT_00B           0x00B
#define EM23_MOT_00C           0x00C
#define EM23_MOT_00D           0x00D
#define EM23_MOT_00E           0x00E
#define EM23_MOT_TAKEOFF_DASH  0x00F
#define EM23_MOT_LANDING       0x010
#define EM23_MOT_TO_CORPSE_012 0x012
#define EM23_MOT_TO_CORPSE_013 0x013
#define EM23_MOT_DIE_NORMAL    0x014
#define EM23_MOT_DM_AIR_015    0x015
#define EM23_MOT_DM_AIR_016    0x016
#define EM23_MOT_TURN          0x017
#define EM23_MOT_EAT           0x018
#define EM23_MOT_TO_CORPSE_01A 0x01A
#define EM23_MOT_TO_CORPSE_01B 0x01B
#define EM23_SEQ_01C           0x01C
#define EM23_SEQ_01D           0x01D
#define EM23_SEQ_TURN_01E      0x01E
#define EM23_SEQ_TURN_01F      0x01F
#define EM23_SEQ_TURN_020      0x020
#define EM23_SEQ_TURN_021      0x021
#define EM23_SEQ_TURN_022      0x022
#define EM23_SEQ_023           0x023
#define EM23_SEQ_024           0x024
#define EM23_SEQ_025           0x025
#define EM23_SEQ_026           0x026
#define EM23_SEQ_027           0x027
#define EM23_SEQ_028           0x028
#define EM23_SEQ_LANDING       0x029
#define EM23_SEQ_DM_AIR        0x02A
#define EM23_SEQ_TO_CORPSE_02B 0x02B
#define EM23_SEQ_TO_CORPSE_02C 0x02C

#endif  // ARC_EM23_H
