// Entries of em24's archive that its code addresses with ARC() / EM_ARC(), generated by
// tools/arc_names.py. MOT is a motion, SEQ a sequence table, BIN a model, TPL textures, ENT an
// empty entry. The word after the type is the routine that plays the motion or the model's
// role; a hex number means the entry has no name yet.
#ifndef ARC_EM24_H
#define ARC_EM24_H

#define EM24_EFF_004          0x004
#define EM24_BIN_005          0x005
#define EM24_TPL_006          0x006
#define EM24_MOT_FREE_007     0x007
#define EM24_MOT_FREE_008     0x008
#define EM24_MOT_FREE_009     0x009
#define EM24_MOT_FREE_00A     0x00A
#define EM24_MOT_COIL         0x00E
#define EM24_MOT_00F          0x00F
#define EM24_MOT_BOX_WAIT_011 0x011
#define EM24_MOT_012          0x012
#define EM24_MOT_DIE_013      0x013
#define EM24_MOT_DIE_015      0x015
#define EM24_MOT_BOX_WAIT_017 0x017
#define EM24_SEQ_BOX_WAIT     0x018
#define EM24_BIN_DIE          0x019
#define EM24_TPL_DIE_01A      0x01A
#define EM24_TPL_DIE_01B      0x01B
#define EM24_TPL_DIE_01C      0x01C

#endif  // ARC_EM24_H
