// Entries of em25's archive that its code addresses with ARC() / EM_ARC(), generated by
// tools/arc_names.py. MOT is a motion, SEQ a sequence table, BIN a model, TPL textures, ENT an
// empty entry. The word after the type is the routine that plays the motion or the model's
// role; a hex number means the entry has no name yet.
#ifndef ARC_EM25_H
#define ARC_EM25_H

#define EM25_BIN_004             0x004
#define EM25_TPL_005             0x005
#define EM25_EFF_007             0x007
#define EM25_MOT_008             0x008
#define EM25_MOT_P_WAIT_009      0x009
#define EM25_MOT_P_WAIT_00A      0x00A
#define EM25_MOT_P_APPEAR        0x00C
#define EM25_SEQ_P_APPEAR        0x00D
#define EM25_MOT_DM_P_NORMAL_00E 0x00E
#define EM25_MOT_DM_P_NORMAL_00F 0x00F
#define EM25_MOT_DIE_P_NORMAL    0x010
#define EM25_MOT_P_ATK           0x013
#define EM25_SEQ_P_ATK           0x014
#define EM25_MOT_P_POISON        0x015
#define EM25_SEQ_P_POISON        0x016
#define EM25_MOT_WAIT            0x019
#define EM25_MOT_WALK            0x01A
#define EM25_SEQ_WALK            0x01B
#define EM25_MOT_RUN             0x01C
#define EM25_SEQ_RUN             0x01D
#define EM25_MOT_TURN90          0x01E
#define EM25_SEQ_TURN90          0x01F
#define EM25_MOT_DIE_NORMAL      0x020
#define EM25_MOT_DM_SMALL        0x021
#define EM25_MOT_DIE_BIG         0x022
#define EM25_SEQ_DIE_BIG         0x023
#define EM25_MOT_024             0x024
#define EM25_SEQ_025             0x025
#define EM25_MOT_026             0x026
#define EM25_MOT_BITE_027        0x027
#define EM25_MOT_029             0x029
#define EM25_SEQ_DM_BIG          0x02A
#define EM25_MOT_BITE_02B        0x02B
#define EM25_SEQ_02E             0x02E
#define EM25_MOT_PL_BITE_02F     0x02F
#define EM25_MOT_PL_BITE_030     0x030
#define EM25_BIN_SET_PARASITE    0x031
#define EM25_TPL_SET_PARASITE    0x032
#define EM25_MOT_SET_PARASITE    0x033

#endif  // ARC_EM25_H
