// Entries of em26's archive that its code addresses with ARC() / EM_ARC(), generated by
// tools/arc_names.py. MOT is a motion, SEQ a sequence table, BIN a model, TPL textures, ENT an
// empty entry. The word after the type is the routine that plays the motion or the model's
// role; a hex number means the entry has no name yet.
#ifndef ARC_EM26_H
#define ARC_EM26_H

#define EM26_BIN_004            0x004
#define EM26_TPL_005            0x005
#define EM26_TPL_006            0x006
#define EM26_EFF_007            0x007
#define EM26_MOT_008            0x008
#define EM26_MOT_WAIT           0x009
#define EM26_MOT_DM_SMALL_00A   0x00A
#define EM26_MOT_DM_SMALL_00B   0x00B
#define EM26_MOT_DM_SMALL_00C   0x00C
#define EM26_MOT_DIE_NORMAL     0x00D
#define EM26_MOT_ATK_00E        0x00E
#define EM26_MOT_ATK_00F        0x00F
#define EM26_MOT_DM_SMALL_010   0x010
#define EM26_SEQ_DIE_NORMAL_011 0x011
#define EM26_SEQ_DIE_NORMAL_012 0x012
#define EM26_SEQ_DIE_NORMAL_013 0x013
#define EM26_SEQ_DIE_NORMAL_014 0x014
#define EM26_SEQ_DIE_NORMAL_015 0x015
#define EM26_SEQ_ATK_016        0x016
#define EM26_SEQ_ATK_017        0x017

#endif  // ARC_EM26_H
