// Entries of em27's archive that its code addresses with ARC() / EM_ARC(), generated by
// tools/arc_names.py. MOT is a motion, SEQ a sequence table, BIN a model, TPL textures, ENT an
// empty entry. The word after the type is the routine that plays the motion or the model's
// role; a hex number means the entry has no name yet.
#ifndef ARC_EM27_H
#define ARC_EM27_H

#define EM27_BIN_004            0x004
#define EM27_TPL_005            0x005
#define EM27_EFF_006            0x006
#define EM27_MOT_007            0x007
#define EM27_MOT_WALK_008       0x008
#define EM27_MOT_WALK_009       0x009
#define EM27_MOT_DASH           0x00A
#define EM27_MOT_TURN180_00B    0x00B
#define EM27_MOT_TURN180_00C    0x00C
#define EM27_MOT_BANK           0x00D
#define EM27_MOT_WAIT           0x00E
#define EM27_MOT_JUMP_00F       0x00F
#define EM27_MOT_JUMP_010       0x010
#define EM27_MOT_DM_NORMAL      0x011
#define EM27_MOT_DM_BIG         0x012
#define EM27_MOT_DM_AIR_013     0x013
#define EM27_MOT_DM_AIR_014     0x014
#define EM27_MOT_DIE_NORMAL_015 0x015
#define EM27_MOT_DM_AIR_016     0x016
#define EM27_MOT_DIE_NORMAL_01B 0x01B
#define EM27_MOT_DIE_NORMAL_01C 0x01C
#define EM27_SEQ_JUMP_01D       0x01D
#define EM27_SEQ_JUMP_01E       0x01E
#define EM27_SEQ_DM_NORMAL      0x01F

#endif  // ARC_EM27_H
