// Entries of em28's archive that its code addresses with ARC() / EM_ARC(), generated by
// tools/arc_names.py. MOT is a motion, SEQ a sequence table, BIN a model, TPL textures, ENT an
// empty entry. The word after the type is the routine that plays the motion or the model's
// role; a hex number means the entry has no name yet.
#ifndef ARC_EM28_H
#define ARC_EM28_H

#define EM28_BIN_004            0x004
#define EM28_TPL_005            0x005
#define EM28_TPL_006            0x006
#define EM28_BIN_WAIT           0x007
#define EM28_TPL_WAIT_008       0x008
#define EM28_TPL_WAIT_009       0x009
#define EM28_TPL_WAIT_00A       0x00A
#define EM28_EFF_00B            0x00B
#define EM28_MOT_00C            0x00C
#define EM28_MOT_WAIT_00D       0x00D
#define EM28_MOT_WALK_00E       0x00E
#define EM28_MOT_WALK_00F       0x00F
#define EM28_MOT_DASH           0x010
#define EM28_MOT_011            0x011
#define EM28_MOT_JUMP_012       0x012
#define EM28_MOT_JUMP_013       0x013
#define EM28_MOT_JUMP_014       0x014
#define EM28_MOT_DIE_AIR_015    0x015
#define EM28_MOT_DIE_AIR_016    0x016
#define EM28_MOT_DIE_NORMAL_017 0x017
#define EM28_MOT_WAIT_018       0x018
#define EM28_MOT_WAIT_019       0x019
#define EM28_MOT_DIE_NORMAL_01A 0x01A
#define EM28_SEQ_DASH           0x01B
#define EM28_SEQ_JUMP_01C       0x01C
#define EM28_SEQ_JUMP_01D       0x01D
#define EM28_SEQ_JUMP_01E       0x01E

#endif  // ARC_EM28_H
