// Entries of em29's archive that its code addresses with ARC() / EM_ARC(), generated by
// tools/arc_names.py. MOT is a motion, SEQ a sequence table, BIN a model, TPL textures, ENT an
// empty entry. The word after the type is the routine that plays the motion or the model's
// role; a hex number means the entry has no name yet.
#ifndef ARC_EM29_H
#define ARC_EM29_H

#define EM29_BIN_004              0x004
#define EM29_TPL_005              0x005
#define EM29_EFF_006              0x006
#define EM29_MOT_007              0x007
#define EM29_MOT_WAIT_CEILING_008 0x008
#define EM29_MOT_WAIT_CEILING_009 0x009
#define EM29_MOT_WAIT_LAND        0x00A
#define EM29_MOT_WALK             0x00B
#define EM29_MOT_00C              0x00C
#define EM29_MOT_TURN_00D         0x00D
#define EM29_MOT_TURN_00E         0x00E
#define EM29_MOT_TURN_00F         0x00F
#define EM29_MOT_DM_RECOVERY      0x010
#define EM29_MOT_DM_LAND          0x011
#define EM29_MOT_ATK_DASH_012     0x012
#define EM29_MOT_ATK_DASH_013     0x013
#define EM29_MOT_ATK_RUSH         0x014
#define EM29_MOT_DM_AIR           0x015
#define EM29_MOT_016              0x016
#define EM29_MOT_017              0x017
#define EM29_MOT_PL_BAT_RUSH      0x018
#define EM29_SEQ_ATK_DASH         0x019

#endif  // ARC_EM29_H
