// Entries of em2a's archive that its code addresses with ARC() / EM_ARC(), generated by
// tools/arc_names.py. MOT is a motion, SEQ a sequence table, BIN a model, TPL textures, ENT an
// empty entry. The word after the type is the routine that plays the motion or the model's
// role; a hex number means the entry has no name yet.
#ifndef ARC_EM2A_H
#define ARC_EM2A_H

#define EM2A_BIN_004                 0x004
#define EM2A_TPL_005                 0x005
#define EM2A_BIN_006                 0x006
#define EM2A_TPL_007                 0x007
#define EM2A_BIN_008                 0x008
#define EM2A_TPL_009                 0x009
#define EM2A_MOT_TRAP1_SET           0x00A
#define EM2A_MOT_00B                 0x00B
#define EM2A_MOT_TRAP1_BREAK         0x00C
#define EM2A_SEQ_TRAP1_BITE          0x00D
#define EM2A_SEQ_TRAP1_BREAK_00E     0x00E
#define EM2A_SEQ_TRAP1_BREAK_00F     0x00F
#define EM2A_MOT_PL_TRAP1_BITE       0x010
#define EM2A_SEQ_PL_TRAP1_BITE       0x011
#define EM2A_EFF_012                 0x012
#define EM2A_MOT_TRAP1_R100          0x013
#define EM2A_SEQ_TRAP1_R100          0x014
#define EM2A_MOT_TRAP1_RESET         0x015
#define EM2A_MOT_TRAP1_BITE_SUB_016  0x016
#define EM2A_MOT_TRAP1_BITE_SUB_017  0x017
#define EM2A_MOT_TRAP1_BITE_SUB_018  0x018
#define EM2A_SEQ_TRAP1_BITE_SUB      0x019
#define EM2A_MOT_SUB_TRAP1_BITE_01A  0x01A
#define EM2A_MOT_SUB_TRAP1_BITE_01B  0x01B
#define EM2A_MOT_SUB_TRAP1_BITE_01C  0x01C
#define EM2A_MOT_PL_EM_RESUCE_ASHLEY 0x01D

#endif  // ARC_EM2A_H
