// Entries of em2e's archive that its code addresses with ARC() / EM_ARC(), generated by
// tools/arc_names.py. MOT is a motion, SEQ a sequence table, BIN a model, TPL textures, ENT an
// empty entry. The word after the type is the routine that plays the motion or the model's
// role; a hex number means the entry has no name yet.
#ifndef ARC_EM2E_H
#define ARC_EM2E_H

#define EM2E_BIN_004 0x004
#define EM2E_TPL_005 0x005
#define EM2E_TPL_006 0x006
#define EM2E_EFF_007 0x007

#endif  // ARC_EM2E_H
