// Entries of em2f's archive that its code addresses with ARC() / EM_ARC(), generated by
// tools/arc_names.py. MOT is a motion, SEQ a sequence table, BIN a model, TPL textures, ENT an
// empty entry. The word after the type is the routine that plays the motion or the model's
// role; a hex number means the entry has no name yet.
#ifndef ARC_EM2F_H
#define ARC_EM2F_H

#define EM2F_BIN_004                  0x004
#define EM2F_TPL_005                  0x005
#define EM2F_BIN_006                  0x006
#define EM2F_TPL_007                  0x007
#define EM2F_EFF_008                  0x008
#define EM2F_MOT_009                  0x009
#define EM2F_MOT_00A                  0x00A
#define EM2F_MOT_SWIM                 0x00D
#define EM2F_MOT_00E                  0x00E
#define EM2F_MOT_SWIM_TURN90_00F      0x00F
#define EM2F_MOT_SWIM_TURN90_010      0x010
#define EM2F_MOT_SWIM_TURN180_ATK_013 0x013
#define EM2F_MOT_SWIM_TURN180_ATK_014 0x014
#define EM2F_MOT_RISING_DRAGON        0x015
#define EM2F_MOT_SWIM_TURN180_ATK_016 0x016
#define EM2F_MOT_017                  0x017
#define EM2F_MOT_SWIM_TURN180_ATK_018 0x018
#define EM2F_MOT_SWIM_TURN180_019     0x019
#define EM2F_MOT_SWIM_TURN180_01A     0x01A
#define EM2F_MOT_CRITICAL             0x01B
#define EM2F_MOT_HIDE_MODE_01C        0x01C
#define EM2F_SEQ_01D                  0x01D
#define EM2F_SEQ_SWIM                 0x01E
#define EM2F_SEQ_01F                  0x01F
#define EM2F_SEQ_SWIM_TURN90_020      0x020
#define EM2F_SEQ_SWIM_TURN90_021      0x021
#define EM2F_SEQ_SWIM_TURN180_ATK_024 0x024
#define EM2F_SEQ_SWIM_TURN180_ATK_025 0x025
#define EM2F_SEQ_RISING_DRAGON        0x026
#define EM2F_SEQ_SWIM_TURN180_ATK_027 0x027
#define EM2F_SEQ_028                  0x028
#define EM2F_SEQ_SWIM_TURN180_ATK_029 0x029
#define EM2F_SEQ_SWIM_TURN180_02A     0x02A
#define EM2F_SEQ_SWIM_TURN180_02B     0x02B
#define EM2F_SEQ_CRITICAL             0x02C
#define EM2F_SEQ_HIDE_MODE_02D        0x02D
#define EM2F_MOT_DIE_NORMAL           0x02E
#define EM2F_BIN_TENTACLE_MOVE        0x02F
#define EM2F_TPL_TENTACLE_MOVE        0x030
#define EM2F_MOT_TENTACLE_MOVE        0x031
#define EM2F_MOT_HIDE_MODE_032        0x032
#define EM2F_SEQ_HIDE_MODE_033        0x033
#define EM2F_SEQ_HIDE_MODE_034        0x034

#endif  // ARC_EM2F_H
