// Entries of em30's archive that its code addresses with ARC() / EM_ARC(), generated by
// tools/arc_names.py. MOT is a motion, SEQ a sequence table, BIN a model, TPL textures, ENT an
// empty entry. The word after the type is the routine that plays the motion or the model's
// role; a hex number means the entry has no name yet.
#ifndef ARC_EM30_H
#define ARC_EM30_H

#define EM30_BIN_004              0x004
#define EM30_TPL_005              0x005
#define EM30_BIN_006              0x006
#define EM30_TPL_007              0x007
#define EM30_BIN_008              0x008
#define EM30_BIN_009              0x009
#define EM30_BIN_00A              0x00A
#define EM30_BIN_00B              0x00B
#define EM30_BIN_00C              0x00C
#define EM30_BIN_00D              0x00D
#define EM30_EFF_00E              0x00E
#define EM30_MOT_00F              0x00F
#define EM30_MOT_WALK             0x010
#define EM30_BIN_SET_PARASITE_012 0x012
#define EM30_TPL_SET_PARASITE_013 0x013
#define EM30_MOT_SET_PARASITE_014 0x014
#define EM30_BIN_SET_PARASITE_015 0x015
#define EM30_TPL_SET_PARASITE_016 0x016
#define EM30_MOT_SET_PARASITE_017 0x017
#define EM30_MOT_SET_PARASITE_018 0x018
#define EM30_MOT_SET_PARASITE_019 0x019
#define EM30_MOT_SET_PARASITE_01A 0x01A
#define EM30_MOT_SET_PARASITE_01B 0x01B
#define EM30_MOT_SET_PARASITE_01C 0x01C
#define EM30_MOT_SET_PARASITE_01D 0x01D
#define EM30_MOT_SET_PARASITE_01E 0x01E
#define EM30_MOT_SET_PARASITE_01F 0x01F
#define EM30_MOT_SET_PARASITE_020 0x020

#endif  // ARC_EM30_H
