// Entries of em34's archive that its code addresses with ARC() / EM_ARC(), generated by
// tools/arc_names.py. MOT is a motion, SEQ a sequence table, BIN a model, TPL textures, ENT an
// empty entry. The word after the type is the routine that plays the motion or the model's
// role; a hex number means the entry has no name yet.
#ifndef ARC_EM34_H
#define ARC_EM34_H

#define EM34_BIN_004      0x004
#define EM34_BIN_005      0x005
#define EM34_BIN_006      0x006
#define EM34_BIN_007      0x007
#define EM34_TPL_008      0x008
#define EM34_BIN_009      0x009
#define EM34_BIN_00A      0x00A
#define EM34_TPL_00B      0x00B
#define EM34_BIN_00C      0x00C
#define EM34_BIN_00D      0x00D
#define EM34_TPL_00E      0x00E
#define EM34_TPL_00F      0x00F
#define EM34_EFF_010      0x010
#define EM34_MOT_011      0x011
#define EM34_MOT_WALK_012 0x012
#define EM34_MOT_WALK_013 0x013
#define EM34_MOT_014      0x014
#define EM34_MOT_ATK      0x015
#define EM34_SEQ_ATK      0x016
#define EM34_MOT_017      0x017
#define EM34_MOT_WALK_018 0x018

#endif  // ARC_EM34_H
