// Entries of em38's archive that its code addresses with ARC() / EM_ARC(), generated by
// tools/arc_names.py. MOT is a motion, SEQ a sequence table, BIN a model, TPL textures, ENT an
// empty entry. The word after the type is the routine that plays the motion or the model's
// role; a hex number means the entry has no name yet.
#ifndef ARC_EM38_H
#define ARC_EM38_H

#define EM38_BIN_004                0x004
#define EM38_BIN_005                0x005
#define EM38_BIN_006                0x006
#define EM38_BIN_007                0x007
#define EM38_TPL_008                0x008
#define EM38_BIN_009                0x009
#define EM38_TPL_00A                0x00A
#define EM38_EFF_00B                0x00B
#define EM38_MOT_00C                0x00C
#define EM38_MOT_WAIT_00D           0x00D
#define EM38_MOT_WAIT_00E           0x00E
#define EM38_MOT_ATK_00F            0x00F
#define EM38_SEQ_ATK                0x010
#define EM38_MOT_ATK_011            0x011
#define EM38_MOT_ATK_012            0x012
#define EM38_MOT_HEAD_STAMP         0x013
#define EM38_SEQ_HEAD_STAMP         0x014
#define EM38_MOT_DM_DOWN_015        0x015
#define EM38_SEQ_DM_DOWN_016        0x016
#define EM38_MOT_DM_DOWN_017        0x017
#define EM38_MOT_DM_DOWN_018        0x018
#define EM38_SEQ_DM_DOWN_019        0x019
#define EM38_MOT_DM_DOWN_01A        0x01A
#define EM38_MOT_DM_DOWN_01B        0x01B
#define EM38_MOT_ATK_HIT            0x01C
#define EM38_MOT_HEAD_UP_01D        0x01D
#define EM38_MOT_HEAD_UP_01E        0x01E
#define EM38_MOT_HEAD_UP_01F        0x01F
#define EM38_MOT_HEAD_UP_020        0x020
#define EM38_SEQ_HEAD_UP_021        0x021
#define EM38_MOT_HEAD_UP_022        0x022
#define EM38_MOT_HEAD_UP_023        0x023
#define EM38_MOT_HEAD_UP_024        0x024
#define EM38_SEQ_HEAD_UP_025        0x025
#define EM38_MOT_HEAD_UP_026        0x026
#define EM38_MOT_HEAD_UP_027        0x027
#define EM38_MOT_DIE_BODY           0x028
#define EM38_MOT_029                0x029
#define EM38_MOT_DM_UPPER_02A       0x02A
#define EM38_MOT_DM_UPPER_02B       0x02B
#define EM38_MOT_U_CRITICAL         0x02C
#define EM38_MOT_DIE_UPPER          0x02E
#define EM38_MOT_02F                0x02F
#define EM38_MOT_030                0x030
#define EM38_MOT_T_OUT              0x031
#define EM38_MOT_T_MDL_ATK          0x032
#define EM38_SEQ_T_MDL_ATK          0x033
#define EM38_MOT_T_ATK_034          0x034
#define EM38_SEQ_T_ATK              0x035
#define EM38_MOT_T_ATK_036          0x036
#define EM38_MOT_T_ATK_037          0x037
#define EM38_MOT_T_DOWN_ATK         0x038
#define EM38_SEQ_T_DOWN_ATK         0x039
#define EM38_MOT_T_BIG_ATK_03A      0x03A
#define EM38_SEQ_T_BIG_ATK_03B      0x03B
#define EM38_MOT_T_BIG_ATK_03C      0x03C
#define EM38_SEQ_T_BIG_ATK_03D      0x03D
#define EM38_MOT_T_CATCH_HIT        0x03E
#define EM38_SEQ_T_CATCH_HIT        0x03F
#define EM38_MOT_SHELL_CONTROL_040  0x040
#define EM38_MOT_SHELL_CONTROL_041  0x041
#define EM38_MOT_SHELL_CONTROL_042  0x042
#define EM38_MOT_SHELL_CONTROL_043  0x043
#define EM38_MOT_SHELL_CONTROL_044  0x044
#define EM38_MOT_PL_ATK_HIT         0x046
#define EM38_MOT_PL_CATCH_HIT_047   0x047
#define EM38_MOT_PL_EM_DM_STAMP_048 0x048
#define EM38_MOT_PL_EM_DM_STAMP_049 0x049
#define EM38_MOT_PL_EM_ESCAPE       0x04A
#define EM38_SEQ_PL_EM_ESCAPE       0x04B
#define EM38_MOT_PL_CATCH_HIT_04C   0x04C
#define EM38_MOT_PL_CKJUMP          0x04E
#define EM38_MOT_PL_EM_SIT          0x04F
#define EM38_MOT_050                0x050
#define EM38_BIN_WEAK_INIT          0x051
#define EM38_TPL_WEAK_INIT          0x052

#endif  // ARC_EM38_H
