// Entries of em3a's archive that its code addresses with ARC() / EM_ARC(), generated by
// tools/arc_names.py. MOT is a motion, SEQ a sequence table, BIN a model, TPL textures, ENT an
// empty entry. The word after the type is the routine that plays the motion or the model's
// role; a hex number means the entry has no name yet.
#ifndef ARC_EM3A_H
#define ARC_EM3A_H

#define EM3A_EFF_004          0x004
#define EM3A_BIN_005          0x005
#define EM3A_TPL_006          0x006
#define EM3A_MOT_007          0x007
#define EM3A_MOT_008          0x008
#define EM3A_BIN_009          0x009
#define EM3A_TPL_00A          0x00A
#define EM3A_BIN_00B          0x00B
#define EM3A_TPL_00C          0x00C
#define EM3A_MOT_00D          0x00D
#define EM3A_MOT_B_MOVE       0x00E
#define EM3A_SEQ_B_MOVE       0x00F
#define EM3A_MOT_010          0x010
#define EM3A_MOT_B_HIDE       0x011
#define EM3A_MOT_012          0x012
#define EM3A_MOT_B_APPEAR     0x013
#define EM3A_MOT_B_DIE        0x014
#define EM3A_MOT_B_APPEAR_DIE 0x015

#endif  // ARC_EM3A_H
