// Entries of em3b's archive that its code addresses with ARC() / EM_ARC(), generated by
// tools/arc_names.py. MOT is a motion, SEQ a sequence table, BIN a model, TPL textures, ENT an
// empty entry. The word after the type is the routine that plays the motion or the model's
// role; a hex number means the entry has no name yet.
#ifndef ARC_EM3B_H
#define ARC_EM3B_H

#define EM3B_BIN_004                0x004
#define EM3B_TPL_005                0x005
#define EM3B_EFF_006                0x006
#define EM3B_MOT_007                0x007
#define EM3B_MOT_TRUCK_RUN_INTO_008 0x008
#define EM3B_MOT_TRUCK_RUN_INTO_009 0x009
#define EM3B_MOT_00A                0x00A
#define EM3B_BIN_00B                0x00B
#define EM3B_TPL_00C                0x00C
#define EM3B_MOT_00D                0x00D
#define EM3B_MOT_00E                0x00E

#endif  // ARC_EM3B_H
