// Entries of em3d's archive that its code addresses with ARC() / EM_ARC(), generated by
// tools/arc_names.py. MOT is a motion, SEQ a sequence table, BIN a model, TPL textures, ENT an
// empty entry. The word after the type is the routine that plays the motion or the model's
// role; a hex number means the entry has no name yet.
#ifndef ARC_EM3D_H
#define ARC_EM3D_H

#define EM3D_EFF_004 0x004
#define EM3D_BIN_005 0x005
#define EM3D_TPL_006 0x006
#define EM3D_BIN_007 0x007
#define EM3D_TPL_008 0x008

#endif  // ARC_EM3D_H
