// Entries of em3e's archive that its code addresses with ARC() / EM_ARC(), generated by
// tools/arc_names.py. MOT is a motion, SEQ a sequence table, BIN a model, TPL textures, ENT an
// empty entry. The word after the type is the routine that plays the motion or the model's
// role; a hex number means the entry has no name yet.
#ifndef ARC_EM3E_H
#define ARC_EM3E_H

#define EM3E_EFF_004           0x004
#define EM3E_BIN_005           0x005
#define EM3E_TPL_006           0x006
#define EM3E_BIN_HEAD_BOMB_007 0x007
#define EM3E_TPL_HEAD_BOMB_008 0x008
#define EM3E_BIN_009           0x009
#define EM3E_TPL_00A           0x00A
#define EM3E_BIN_HEAD_BOMB_00B 0x00B
#define EM3E_TPL_HEAD_BOMB_00C 0x00C
#define EM3E_BIN_00D           0x00D
#define EM3E_TPL_00E           0x00E
#define EM3E_BIN_00F           0x00F
#define EM3E_TPL_010           0x010
#define EM3E_BIN_HEAD_BOMB_011 0x011
#define EM3E_TPL_HEAD_BOMB_012 0x012
#define EM3E_BIN_SET_EFF       0x013
#define EM3E_TPL_SET_EFF       0x014
#define EM3E_BIN_015           0x015
#define EM3E_TPL_016           0x016

#endif  // ARC_EM3E_H
