// Entries of pl0e's archive that its code addresses with ARC() / EM_ARC(), generated by
// tools/arc_names.py. MOT is a motion, SEQ a sequence table, BIN a model, TPL textures, ENT an
// empty entry. The word after the type is the routine that plays the motion or the model's
// role; a hex number means the entry has no name yet.
#ifndef ARC_PL0E_H
#define ARC_PL0E_H

#define PL0E_EFF_004             0x004
#define PL0E_BIN_005             0x005
#define PL0E_TPL_006             0x006
#define PL0E_BIN_PL_RIDE         0x007
#define PL0E_MOT_RAIL_MOVE_008   0x008
#define PL0E_MOT_RAIL_MOVE_009   0x009
#define PL0E_MOT_RAIL_MOVE_00A   0x00A
#define PL0E_MOT_JUMP_00B        0x00B
#define PL0E_MOT_JUMP_00C        0x00C
#define PL0E_MOT_CRASH           0x00D
#define PL0E_MOT_JUMP_00E        0x00E
#define PL0E_MOT_RIDE            0x00F
#define PL0E_MOT_JUMP_010        0x010
#define PL0E_MOT_JUMP_011        0x011
#define PL0E_MOT_SINK            0x012
#define PL0E_MOT_JUMP_MISS       0x013
#define PL0E_MOT_JUMP_014        0x014
#define PL0E_MOT_PL_MOVE_016     0x016
#define PL0E_MOT_PL_MOVE_017     0x017
#define PL0E_MOT_PL_MOVE_018     0x018
#define PL0E_MOT_PL_JUMP_019     0x019
#define PL0E_MOT_PL_LANDING_01A  0x01A
#define PL0E_MOT_PL_CRASH_01B    0x01B
#define PL0E_MOT_PL_JUMP_01C     0x01C
#define PL0E_MOT_PL_RIDE         0x01D
#define PL0E_MOT_PL_LANDING_01E  0x01E
#define PL0E_MOT_PL_LANDING_01F  0x01F
#define PL0E_MOT_PL_CRASH_020    0x020
#define PL0E_MOT_PL_SINK         0x021
#define PL0E_MOT_PL_JUMP_MISS    0x022
#define PL0E_MOT_PL_JUMP_023     0x023
#define PL0E_MOT_SUB_RUN_025     0x025
#define PL0E_MOT_SUB_RUN_026     0x026
#define PL0E_MOT_SUB_RUN_027     0x027
#define PL0E_MOT_SUB_JUMP_028    0x028
#define PL0E_MOT_SUB_LANDING_029 0x029
#define PL0E_MOT_SUB_CRASH       0x02A
#define PL0E_MOT_SUB_JUMP_02B    0x02B
#define PL0E_MOT_SUB_RIDE        0x02C
#define PL0E_MOT_SUB_LANDING_02D 0x02D
#define PL0E_MOT_SUB_LANDING_02E 0x02E
#define PL0E_MOT_SUB_SINK        0x02F
#define PL0E_MOT_SUB_JUMP_MISS   0x030
#define PL0E_MOT_SUB_JUMP_031    0x031

#endif  // ARC_PL0E_H
