// Entries of pl0f's archive that its code addresses with ARC() / EM_ARC(), generated by
// tools/arc_names.py. MOT is a motion, SEQ a sequence table, BIN a model, TPL textures, ENT an
// empty entry. The word after the type is the routine that plays the motion or the model's
// role; a hex number means the entry has no name yet.
#ifndef ARC_PL0F_H
#define ARC_PL0F_H

#define PL0F_EFF_004                 0x004
#define PL0F_BIN_005                 0x005
#define PL0F_TPL_006                 0x006
#define PL0F_BIN_PL_SET_SPEAR        0x007
#define PL0F_BIN_008                 0x008
#define PL0F_MOT_009                 0x009
#define PL0F_MOT_00A                 0x00A
#define PL0F_MOT_00B                 0x00B
#define PL0F_MOT_PL_SPEAR_SET        0x00C
#define PL0F_MOT_00D                 0x00D
#define PL0F_MOT_00E                 0x00E
#define PL0F_MOT_00F                 0x00F
#define PL0F_MOT_010                 0x010
#define PL0F_MOT_011                 0x011
#define PL0F_MOT_012                 0x012
#define PL0F_MOT_013                 0x013
#define PL0F_MOT_PL_SWIM             0x014
#define PL0F_SEQ_PL_SWIM_015         0x015
#define PL0F_SEQ_PL_SWIM_016         0x016
#define PL0F_SEQ_PL_SWIM_017         0x017
#define PL0F_SEQ_PL_SWIM_018         0x018
#define PL0F_SEQ_PL_SWIM_019         0x019
#define PL0F_SEQ_PL_SWIM_01A         0x01A
#define PL0F_SEQ_PL_SWIM_01B         0x01B
#define PL0F_SEQ_PL_SWIM_01C         0x01C
#define PL0F_MOT_01D                 0x01D
#define PL0F_MOT_PL_GUARD            0x01E
#define PL0F_MOT_DROP                0x01F
#define PL0F_MOT_PL_FALL_WATER       0x020
#define PL0F_MOT_PL_WATER_RIDE       0x021
#define PL0F_MOT_WATER_RIDE          0x022
#define PL0F_BIN_LONG_ROPE_SET       0x023
#define PL0F_TPL_LONG_ROPE_SET       0x024
#define PL0F_BIN_SET_ANCHOR          0x025
#define PL0F_TPL_SET_ANCHOR          0x026
#define PL0F_MOT_PL_SPEAR_SET2       0x027
#define PL0F_MOT_PL_DIE              0x028
#define PL0F_MOT_029                 0x029
#define PL0F_MOT_PL_GETOFF           0x02A
#define PL0F_MOT_SUB_RIDE            0x02B
#define PL0F_MOT_02C                 0x02C
#define PL0F_MOT_SUB_GETOFF          0x02D
#define PL0F_MOT_SET_ANCHOR_EM2F_02E 0x02E
#define PL0F_MOT_SET_ANCHOR_EM2F_02F 0x02F
#define PL0F_MOT_SET_ANCHOR_EM2F_030 0x030

#endif  // ARC_PL0F_H
